---
# Change the awesome-cv.cls file in the folder with following section, for better shade of black for the text.
# % Gray-scale colors
# \definecolor{white}{HTML}{FFFFFF}
# \definecolor{black}{HTML}{000000}
# \definecolor{darkgray}{HTML}{333333}
# \definecolor{gray}{HTML}{333333}
# \definecolor{lightgray}{HTML}{999999}
# \geometry{left=2.0cm, top=1.5cm, right=1.5cm, bottom=1.5cm, footskip=.5cm}
name: "**Sanjiv Kumar**"
position: "Ph.D. Biotechnology"
aboutme: "Molecular Biology, Biotechnology, Protein Biochemistry, Bacteriology, Bioinformatics"
# address: "Division of Glycoscience, School of Biotechnology @ KTH Royal Institute of Technology"
# address: \textbf{Division of Glycoscience, School of Biotechnology @ KTH Royal Institute of Technology}
phone: +46 076 057 62 08
email: "sanjiv@kth.se"
github: sanjiv856
linkedin: sanjiv-kumar-b246b44a
orcid: 0000-0003-3514-8999
headcolor: 414141
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv
# header-includes:
#   \usepackage{fontawesome}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(fontawesome)
# load.fontawesome()
```
# Research Interests

Highly efficient molecular biologist, with focus on Protein Biochemistry and Infection Biology • Adept at _in-silico_ characterization of proteins (phylogenetic analysis, homology modeling, drug discovery, molecular docking and simulations etc.) • Knowledge and experience of Genomics, metagenomics and RNA-Seq data analyses tools and software • Efficient at the techniques in the context of drug discovery against infectious pathogens

# Technical Skills

Molecular biology techniques, Microbiology techniques, Protein biochemistry, Protein crystallography, Drug discovery, Bioinformatics (Pharmaceutical Bioinformatics, Genomic and Metagenomics data analysis), R[Intermediate], Python[Intermediate], bash. Adept user of UNIX.

# Research Experience

**<span style="font-size:1em;">Division of Glycoscience, School of Biotechnology, KTH Royal Institute of Technology</span>** \hfill _Stockholm, Sweden_  
Researcher, Oomycetes Biology  \hfill _August 2017 - Present_  

As a researcher with the Vaibhav Srivastava's Lab, I am responsible for the development and implementation of research strategy towards novel anti-infectives against Oomycete pathogens. Including following roles:

 - Expression, purification and biochemical characterization of proteins involved in cell-wall biogenesis from Oomycete pathogens, Horizon 2020 project 
 - Cell wall linkage analysis of various Oomycete pathogens, Horizon 2020 project
 - Identification and characterization of protein targets and inhibitors important for disease control strategies against _Saprolegnia parasitica_ and their _in-vitro_ assessment.

**<span style="font-size:1em;">Justin Radolf  Lab at University of Connecticut Health Center</span>** \hfill _Connecticut, USA_  
Post-Doctoral Fellow, Infectious Biology \hfill _April 2015 - August 2017_  

As a Post-Doctoral Fellow at UConn Health, I was involved with the characterization of rare Outer Membrane Proteins (OMPs) in _Treponema pallidum_. Including following roles:

 - Consensus computational framework to identify rare OMPs in _T. pallidum_
 - Biophysical and experimental characterization of BAM – complex in _T. pallidum_ 
 - Identification and analysis of sequence variations in _T. pallidum_ from clinical samples

**<span style="font-size:1em;">Vineet Sharma Lab at Indian Institute of Science Education and Research, Bhopal (IISER-B)</span>** \hfill _Bhopal, India_  
Post-Doctoral Fellow, Metagenomics and Systems Biology \hfill _December 2013 - February 2015_  

As a Post-Doctoral Fellow at MetaBioSys lab, I was responsible for the Metagenomic analysis of human gut and polluted river microbiomes. Some of the roles included:

 - Reconstruction of bacterial and viral genomes from multiple human gut metagenomes
 - Development of prediction tool for peptidoglycan hydrolases from bacterial genomes
 - De novo assembly of genomes from human gut metagenomic data

**<span style="font-size:1em;">S. Ramachandran Lab, Institute of Genomics and Integrative Biology</span>** \hfill _New Delhi, India_  
Junior Research Fellow, Genomics and Integrative Biology \hfill _December 2007 - February 2015_  

As a Junior Research Fellow, I was responsible for the identification of novel adhesins from _Mycobacterium tuberculosis_, including • Identification of novel potential adhesins of _M. tuberculosis_ H37RV and their experimental validation • Characterization of a novel N-acetylmuramoyl-L-alanine amidase Rv3717 from _M. tuberculosis_ H37Rv

# Patent Filed
 - Vaibhav Srivastava, **Sanjiv Kumar**, and Vincent Bulone (2020). “Treatment of saprolegniasis.” International Patent Application No.PCT/SE2020/050468, Filing date: May 7, 2020.  [[Link](https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2020246927)]

# Awards
KTH Innovation Challenge Tech for the Global Goals award of 50000 SEK, jointly shared with Vaibhav Srivastava, awarded by KTH Royal Institute of Technology, Stockholm, Sweden (May 2018)
•	Senior Research Fellowship from CSIR, New Delhi, India (March 2009 – February 2012)
•	Junior Research Fellowship from CSIR, New Delhi, India, (March 2007 – February 2009)
•	Defense Scholarship during graduation (B. V. Sc. & A. H.) (1998-2003)

# Education
**<span style="font-size:1em;">Institute of Genomics and Integrative Biology (CSIR-IGIB)</span>** \hfill _Delhi, India_  
Ph.D. in Biotechnology \hfill _2014_

**<span style="font-size:1em;">Lala Lajpat Rai University of Veterinary and Animal Sciences</span>** \hfill _Haryana, India_  
Masters in Veterinary Sciences (M.V.Sc.), Veterinary Microbiology \hfill _2007_

**<span style="font-size:1em;">Veterinary College, KVAFS University</span>** \hfill _Bangalore, Karnataka, India_  
Bachelor of Veterinary Sciences & Animal Husbandry (B.V.Sc. & A.H.) \hfill _2004_

# Training

**Pharmaceutical Bioinformatics**, Grade: **VG**, Uppsala University, _Uppsala, Sweden_, _Aug. 31 - Nov. 01, 2020_ [[Credential](https://drive.google.com/file/d/12iLN_v139fyi-sXLBS6Dflrhapb81U2g/view?usp=sharing)] • **Applied Pharmaceutical Structural Bioinformatics**, Grade: **VG**, Uppsala University, _Uppsala, Sweden_, _Aug. 31 - Oct.r 15, 2020_ [[Credential](https://drive.google.com/file/d/12iLN_v139fyi-sXLBS6Dflrhapb81U2g/view?usp=sharing)] • **RNA-Seq Data Analysis**, Workshop by National Bioinformatics Infrastructure Sweden (**NBIS**) and **SciLifeLab**, _Uppsala, Sweden_, _May 13 - 15, 2019_  [[Credential](https://drive.google.com/file/d/1q346hxeIJr0rdkLO_Z9K-4v88jdMH8KM/view?usp=sharing)]. 

# Independent Coursework
**Intro to Machine Learning**, Kaggle, _Mar. 2021_ [[Credential](https://www.kaggle.com/learn/certification/sanjiv856/intro-to-machine-learning)]  • **Python**, Kaggle, _Mar. 2021_ [[Credential](https://www.kaggle.com/learn/certification/sanjiv856/python)] • **Automate the Boring Stuff with Python Programming**, Udemy, _Jun. 2019_ [[Credential](https://udemy-certificate.s3.amazonaws.com/pdf/UC-GUFI85SI.pdf)] • **Python Programming Bootcamp**, Udemy, _Jun. 2019_ [[Credential](https://www.datacamp.com/statement-of-accomplishment/course/825c18da84c0cc7653bf4b1928d9550b6b4ab461)] • **Python for Absolute Beginners**, Udemy, _Jun. 2019_ [[Credential](https://www.udemy.com/certificate/UC-I6SOJON2/)] • **Introduction to Python**, DataCamp, _April 2019_ [[Credential](https://www.datacamp.com/statement-of-accomplishment/course/825c18da84c0cc7653bf4b1928d9550b6b4ab461)] • **Introduction to R Course**, DataCamp, _Nov. 2017_ [[Credential](https://www.datacamp.com/statement-of-accomplishment/course/a680518c646e1e99598e3f2f47b5fb659f4d86ec)].

# Publications (Since 2018)
For a complete list of publications please see [*My Google Scholar Profile*](https://scholar.google.com/citations?user=ML7X29AAAAAJ&hl=en).

First Author Peer-Reviewed Publications – **6** • Total Peer-Reviewed Publications – **19** • Popular Science Articles – **1**.

1.	Srivastava, A., Biswas, S., Yadav, S., **Kumar, S**., Srivastava, V., & Mishra, Y. (**2021**). Acute cadmium toxicity and post-stress recovery: Insights into coordinated and integrated response/ recovery strategies of _Anabaena sp._ PCC 7120. _**Journal of Hazardous Materials**_. [[ScienceDirect](https://www.sciencedirect.com/science/article/pii/S0304389420328132)]
2. **Kumar, S.**, Mandal, R.S., Bulone, V. & Srivastava, V. (**2020**). Identification of growth inhibitors of the fish pathogen _Saprolegnia parasitica_ using in silico subtractive proteomics, computational modelling, and biochemical validation. _**Frontiers in Microbiology**_ 11, 2533. [[PubMed](https://pubmed.ncbi.nlm.nih.gov/33178154/)]
3.	Murugan, N.A., **Kumar, S.**, Jeyakanthan, J. & Srivastava, V. (**2020**). Searching for target-specific and multi-targeting organics for COVID-19 in the Drugbank database with a double scoring approach. _**Scientific Reports**_ 10(1), 19125. [[Scientific Reports](https://www.nature.com/articles/s41598-020-75762-7)]
4.	Yadav, S., Srivastava, A., Biswas, S., Chaurasia, N., Singh, S.K., **Kumar, S.**, Srivastava, V. & Mishra, Y. (**2020**) Comparison and optimization of protein extraction and two-dimensional gel electrophoresis protocols for liverworts. _**BMC Research Notes**_ 13, 60. [[PubMed](https://pubmed.ncbi.nlm.nih.gov/32028996/)]
5.	Mittal, P., PK, V.P., Dhakan, D.B., **Kumar, S.** & Sharma, V.K. (**2019**) Metagenome of a polluted river reveals a reservoir of metabolic and antibiotic resistance genes. _**Environmental Microbiome**_, 14: 5. [[BioMed Central](https://environmentalmicrobiome.biomedcentral.com/articles/10.1186/s40793-019-0345-3)]
6.	Kaur, S., Srivastava, A., **Kumar, S.**, Srivastava, V., Ahluwalia, A.S. and Mishra, Y., (**2019**). Biochemical and proteomic analysis reveals oxidative stress tolerance strategies of _Scenedesmus abundans_ against allelochemicals released by _Microcystis aeruginosa_. _**Algal Research**_, 41, p.101525. [[ScienceDirect](https://www.sciencedirect.com/science/article/pii/S2211926419302656)]
7.	**Kumar, S.**, Caimano, M. J., Anand, A., Dey, A., Hawley, K. L., LeDoyt, M., La Vake, C., Cruz, A. R., Ramirez, L. G., Pastekova, L., Bezsonova I, Smajs D, Salazar J. C., & Radolf J. D. (**2018**) Sequence variation of rare outer membrane protein β-barrel domains in clinical strains provides insights into the evolution of _Treponema pallidum_ subsp. pallidum, the syphilis spirochete. _**mBio**_ 9(3): e01006-18.[[PubMed](https://pubmed.ncbi.nlm.nih.gov/29895642/)]

# References
References will be provided upon request.